/*--------------------------------------------------------------------------------------------------
 * Author:      Dan Cassidy
 * Date:        2015-07-13
 * Assignment:  HW3-4
 * Source File: NumberConverter.java
 * Language:    Java
 * Course:      CSCI-C 490, Android Programming, MoWe 08:00
--------------------------------------------------------------------------------------------------*/
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * Small GUI-based program to convert a base ten number into a base two number.
 * 
 * @author Dan Cassidy
 */
public class NumberConverter extends JFrame implements ActionListener
{
    private JTextField textBaseTen;
    private JTextField textBaseTwo;
    
    /**
     * Entry point for the class.
     * 
     * @param args Command line arguments. <i>Ignored</i>.
     */
    public static void main(String[] args)
    {
        NumberConverter gui = new NumberConverter();
        gui.setVisible(true);
    }
    
    /**
     * Default constructor. Handles the setup of all the GUI elements.
     */
    public NumberConverter()
    {
        super("Number Converter");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        
        // Set up the labels and input text boxes.
        JPanel inputPanel = new JPanel();
        inputPanel.setLayout(new GridLayout(2, 2));
        
        JLabel labelBaseTen = new JLabel("Input a number in base ten: ");
        inputPanel.add(labelBaseTen);
        
        textBaseTen = new JTextField();
        inputPanel.add(textBaseTen);
        
        JLabel labelBaseTwo = new JLabel("Your number in base two: ");
        inputPanel.add(labelBaseTwo);
        
        textBaseTwo = new JTextField();
        inputPanel.add(textBaseTwo);
        
        add(inputPanel, BorderLayout.NORTH);
        
        // Set up the buttons.
        JPanel buttonsPanel = new JPanel();
        buttonsPanel.setLayout(new FlowLayout());
        
        JButton buttonConvert = new JButton("Convert");
        buttonConvert.addActionListener(this);
        buttonsPanel.add(buttonConvert);
        
        JButton buttonClear = new JButton("Clear");
        buttonClear.addActionListener(this);
        buttonsPanel.add(buttonClear);
        
        add(buttonsPanel, BorderLayout.SOUTH);
        
        // Make the UI arrange itself.
        pack();
    }
    
    /**
     * Handles events generated by the buttons.
     * 
     * @param e Specifies the generated event.
     */
    @Override
    public void actionPerformed(ActionEvent e)
    {
        String buttonString = e.getActionCommand();
        
        // Convert button was clicked.
        if (buttonString.equals("Convert"))
        {
            try
            {
                textBaseTwo.setText(convertToBaseTwo(textBaseTen.getText()));
            }
            catch (IllegalArgumentException ex)
            {
                textBaseTen.setText("Error: Invalid number.");
            }
            catch (Exception ex)
            {
                textBaseTen.setText(ex.getMessage());
                ex.printStackTrace();
            }
            textBaseTen.requestFocus();
        }
        // Clear button was clicked.
        else if (buttonString.equals("Clear"))
        {
            textBaseTen.setText("");
            textBaseTwo.setText("");
            textBaseTen.requestFocus();
        }
        // Error.
        else
            System.out.println("Unexpected error.");
    }
    
    /**
     * Converts a base ten number into a base two number.
     * 
     * @param inputNumber Contains the number to be converted from base ten to base two.
     * @return String, holding the number to be displayed.
     * @throws NumberFormatException if <b>inputNumber</b> cannot be parsed into an integer.
     * @throws IllegalArgumentException if <b>inputNumber</b> is negative.
     */
    private String convertToBaseTwo(String inputNumber)
    {
        String result = "";
        
        // Try to parse the input string, then check if the number is good. If parsing fails or the
        // number is bad, exceptions are thrown.
        int number = Integer.parseInt(inputNumber);
        if (number < 0)
            throw new IllegalArgumentException();
            
        // Handle the number.
        if (number == 0)
            result = "0";
        else
            while (number != 0)
            {
                result = (number % 2) + result;
                number /= 2;
            }
            
        return result;
    }
    
}
